module.exports = {
  LOGIN_MODAL: 'LOGIN_MODAL',
  ERROR_MODAL: 'ERROR_MODAL',
  SOON_MODAL: 'SOON_MODAL',
  EXCHANGE_MODAL: 'EXCHANGE_MODAL',
  mapStyle: {
    WATER_COLOR:'#241c4a',
    LAND_COLOR: '#393174',
    STROKE_COLOR: '#47399f',
    TOPO110_STROKE_WIDTH: 0.25,
    TOPO50_STROKE_WIDTH: 0.15,
  },
  mapSettings: {
    MAX_ZOOM: 10.8,
    MIN_ZOOM: 0.5,
    MIN_ZOOM_MOBILE: 1,
    ZOOM_STEPS: 1.1,
    CENTER_ZOOM: 2.5,
    CENTER_ZOOM_MOBILE: 5.4,
    MAX_ZOOM_MOBILE: 12.2
  },
  buySell: {
    DEFAULT_PRICE_CHANGE: 2
  }
}
