export const LOGIN_MODAL = 'LOGIN_MODAL'
export const WRONG_NETWORK_MODAL = 'WRONG_NETWORK_MODAL'
export const SOON_MODAL = 'SOON_MODAL'
export const EXCHANGE_MODAL = 'EXCHANGE_MODAL'
export const LOADING_MODAL = 'LOADING_MODAL'
export const METAMASK_ACCOUNT_MODAL = 'METAMASK_ACCOUNT_MODAL'
export const PRICE_EXPLANATION_MODAL = 'PRICE_EXPLANATION_MODAL'

export const mapStyle = {
  WATER_COLOR: '#241c4a',
  LAND_COLOR: '#393174',
  STROKE_COLOR: '#47399f',
  TOPO110_STROKE_WIDTH: 0.25,
  TOPO50_STROKE_WIDTH: 0.15
}

export const mapSettings = {
  MAX_ZOOM: 10.8,
  MIN_ZOOM: 0.5,
  MIN_ZOOM_MOBILE: 1,
  ZOOM_STEPS: 1.1,
  CENTER_ZOOM: 2.5,
  CENTER_ZOOM_MOBILE: 5.4,
  MAX_ZOOM_MOBILE: 12.2
}
